# config file for stripes2rqtl.snek

## input
input_folder:
  "/home/tilman/nas/stripes_AIL_gg6a/F8/stripes_data/with.fam.f2.call2.Genotype/"
tiger_folder:
  "/home/tilman/nas/stripes_AIL_gg6a/F8/stripes_data/with.fam.f2.call2.TIGER_OUT"
pedigree_file:
  /home/tilman/nas/stripes_AIL_gg6a/F8/stripes_data/input_aux/combined_pedigree_20181217.tsv
phenotype_file:
  /home/tilman/nas/stripes_AIL_gg6a/F8/bw8_nona.csv
chr_ranks_file:
  /home/tilman/nas/stripes_AIL_gg6a/F8/stripes_data/input_aux/Index_fastq_contig_chr.txt
## output:
outfolder:
  "/home/tilman/nas/stripes_AIL_gg6a/F8/stripes2rqtl"

## parameter for format_in_r
cutoff:
  10 # minimum number of markers
binsize:
  1000000 # size of bins in basepairs, i.e. 1mb


## parameter for filter_gt_xo_size
xo_minsize:
  3

## parameter for make_rqtl_input:
generation:
  08
jitter:
  0.2
