# The reference genome, used for the mapping
reference:
  /proj/snic2019-8-287/test_data/reference/ref_unzipped/GCF_000002315.5_GRCg6a_genomic.fna

# If we want to have an output that contains only the sites selected between 2 lines #TODO needed? FIXME
selectBetweenLines:
  /home/tilman/storage2/stripes_2_data/Founder_fixed_sites_chr_sites.txt

# Folder containing the fastq (considered as paired and named {sample}_forward.fastq.gz and {sample}_reverse.fastq.gz)
Raw_Folder:
  /proj/snic2019-8-287/test_data/raw

# file containing all sample wildcards, in case no individual input files are there anymore
# TODO have this derived from the VCF samples ?
sample_file:
  ../../test_data/aux/samples.txt
  

conda:
  ./config/env.yaml

python:
  /crex/proj/snic2019-8-287/Stripes/stripes/.snakemake/conda/c2815089/bin/python

# The VCF file of founders (created separatly with a more classic approach, in our case GATK and a joined call)
founders:
  /proj/snic2019-8-287/test_data/aux/allGQ20_MQ50_noIndels_callrate0.3_test_founders.vcf

TIGER_WD:
  /proj/snic2019-8-287/test_data/tiger

CALL_WD:
  VCF

cohort:
  /proj/snic2019-8-287/test_data/test_two_samples.vcf

# Was used to test the difference of quality in pipeline using markers fixed in family and in line
indiv:
  fam:
    with.fam.f2.call2.
#  lines: with.lines.f2.call2.

# To create a folder of the VCFs
CALLING_SUFFIX:
  Call

# To create a folder for individual genotypes per sample
GENOTYPE_SUFFIX:
  Genotype


# The results of TIGER, one subfolder per sample, splited by chromosomes
TIGER_SUFFIX:
  TIGER_OUT


# A file with the chromosomes and their size in base (see example)
genomeSizeFile:
  /proj/snic2019-8-287/test_data/size.genome

# java options for rule caller and rule estimate:                                                                                                                    
java_options:
  -Xmx4G

# Number of SNP per windows
winsize:
  50

# Number of scaffolds to treat (Take the scaffold numbered (1-scaffoldNumber), the methods is not working well for smaller scaffold
scaffoldNumber:
  3

# The pedigree file (see example for format)
pedigree:
  /proj/snic2019-8-287/test_data/aux/AIL_pedigree_20190826.tsv

# File containing the full names (from the reference, a rank (col 3) and the size of the chromosomes
contigNames:
 /proj/snic2019-8-287/test_data/aux/Index_fastq_contig_chr.txt


# If not in the script folder use an absolute path
individualGenotypes2breaksPath:
  scripts/individualGenotypes2breaks

high:
  /proj/snic2019-8-287/test_data/aux/high_full.txt
low:
  /proj/snic2019-8-287/test_data/aux/low_full.txt
generation:
  2
